"""timeee

Revision ID: 57aaec59bac8
Revises: 9b94e96ad0d0
Create Date: 2024-10-03 21:47:12.204793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57aaec59bac8'
down_revision: Union[str, None] = '9b94e96ad0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
                    server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'update_at',
                    server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
                    server_default=None)
    op.alter_column('users', 'update_at',
                    server_default=None)
    # ### end Alembic commands ###
