"""add column User.is_verification_email

Revision ID: 9b94e96ad0d0
Revises: 3c6d5389ef4d
Create Date: 2024-09-29 16:34:42.729857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b94e96ad0d0'
down_revision: Union[str, None] = '3c6d5389ef4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verification_email', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verification_email')
    # ### end Alembic commands ###
