"""add catalog v1

Revision ID: 1fe758610e9d
Revises: 1807bc2c23d3
Create Date: 2024-09-06 19:25:10.129056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe758610e9d'
down_revision: Union[str, None] = '1807bc2c23d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('finish_year', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_moneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.Column('ruler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ruler_id'], ['rulers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moneys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('photo_link', sa.String(), nullable=True),
    sa.Column('type_money_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_money_id'], ['types_moneys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneys')
    op.drop_table('types_moneys')
    op.drop_table('rulers')
    # ### end Alembic commands ###
