"""create table messanger

Revision ID: e93d2e810b89
Revises: 90752f5b78f2
Create Date: 2025-01-05 16:56:40.395282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93d2e810b89'
down_revision: Union[str, None] = '90752f5b78f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messanger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messanger_recipient_id'), 'messanger', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messanger_sender_id'), 'messanger', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messanger_sender_id'), table_name='messanger')
    op.drop_index(op.f('ix_messanger_recipient_id'), table_name='messanger')
    op.drop_table('messanger')
    # ### end Alembic commands ###
